version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: spacesync
      POSTGRES_PASSWORD: spacesync
      POSTGRES_DB: spacesync
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: spacesync
      POSTGRES_PASSWORD: spacesync
      POSTGRES_DB: spacesync
      REDIS_HOST: redis
      REDIS_PORT: 6379

volumes:
  postgres_data:
  redis_data: 