apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacesync-backend
  labels:
    app: spacesync-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spacesync-backend
  template:
    metadata:
      labels:
        app: spacesync-backend
    spec:
      containers:
      - name: spacesync-backend
        image: spacesync-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "spacesync"
        - name: POSTGRES_PASSWORD
          value: "spacesync"
        - name: POSTGRES_DB
          value: "spacesync"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: spacesync-backend-service
spec:
  selector:
    app: spacesync-backend
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP 